name: "UUSD Arbitrage Bot"

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch:

jobs:
  compute:
    name: "UUSD Arbitrage Bot"
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}
    env:
      HOT_WALLET_PRIVATE_KEY: ${{ secrets.HOT_WALLET_PRIVATE_KEY }}

    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Run UUSD Arbitrage Bot
        run: bun ./src/action.ts